#version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tocupboard-wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: tocupboard-wp-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 300
      STRIPE_TEST_PK: pk_test_51S6zUAQNNra13I4fglIaQzInaPsIKQGmhsWaG1EG7fBz7uoxk3bFjg5MhCFKQeZ2Gc2BbjUBV4pjB8sB6Otebl6J00j3AevUla
      STRIPE_TEST_SK: sk_test_51S6zUAQNNra13I4fVBrh72A9Y1CMR80MePFtjic6TEQGOmaWQvgCmgSlrkUMirUGD8MVoOuOaAkU8JCTWcuiV2TX00kigKimMC
      WORDPRESS_CONFIG_EXTRA: |
        /* SSL Settings */
        define('FORCE_SSL_ADMIN', true);
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            $$_SERVER['HTTPS'] = 'on';
        }
    volumes:
      - wp_data:/var/www/html
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: tocupboard-wp-nginx
    ports:
      - "80:80"  # Puerto HTTP
      - "8080:443" # Puerto HTTPS
    volumes:
      - wp_data:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/csp.conf:/etc/nginx/conf.d/csp.conf:ro
      - ./ssl:/etc/nginx/ssl:ro # Mapear certificados SSL
    depends_on:
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: tocupboard-wp-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
  wp_data:
