version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tocupboard-wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tocupboard-wp-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: tocupboard-wp-nginx
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./csp.conf:/etc/nginx/conf.d/csp.conf:ro
    depends_on:
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: tocupboard-wp-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
  wp_data:
